spring:
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  application:
    name: crm-application
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
