spring:
  application:
    name: crm-application
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: ${DATASOURCE_DIALECT}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: ${HIBERNATE_USE_JDBC_METADATA_DEFAULTS}